### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'commands')

### ISSUE THREAD

**Issue by AudiRoCWA** [Discord-Robots/Discord.js-v14-Template#1]
developerGuild.commands
                 ^

TypeError: Cannot read properties of undefined (reading 'commands')

 at loadCommands (C:\Users\*\Downloads\Discord.js-v14-Template-main\Discord.js-v14-Template-main\Handlers\Commands.js:45:18)

**Comment by Peter-MJ-Parker** [comment]
Please make sure you have set the `DevGuild` id in your .env

**Comment by Peter-MJ-Parker** [comment]
@AudiRoCWA I have updated the template repo to use the correct .env formatting. Please check it out for the issue resolution.
