### ISSUE TITLE
Bugged?

### ISSUE THREAD

**Issue by NovaNinjaa** [Discord-Robots/Discord.js-v14-Template#2]
```
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module './Structures/Utils'
Require stack:
- /home/runner/ServerGuard-1/Structures/bot.js
- /home/runner/ServerGuard-1/index.js
```

How do i fix?

**Comment by Peter-MJ-Parker** [comment]
> ```
> node:internal/modules/cjs/loader:998
>   throw err;
>   ^
> 
> Error: Cannot find module './Structures/Utils'
> Require stack:
> - /home/runner/ServerGuard-1/Structures/bot.js
> - /home/runner/ServerGuard-1/index.js
> ```
> 
> How do i fix?

Sorry for the late reply. I have updated the code. Please see the latest commit [here](https://github.com/Discord-Robots/Discord.js-v14-Template/tree/f480fde3571f21b2edf79f33c52edf649fed4155#:~:text=Peter%2DMJ%2DParker-,refactor%3A%20update%20bot.js,-%E2%80%A6).
